
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `CredentialShare` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model CredentialShare
 * 
 */
export type CredentialShareModel = runtime.Types.Result.DefaultSelection<Prisma.$CredentialSharePayload>

export type AggregateCredentialShare = {
  _count: CredentialShareCountAggregateOutputType | null
  _min: CredentialShareMinAggregateOutputType | null
  _max: CredentialShareMaxAggregateOutputType | null
}

export type CredentialShareMinAggregateOutputType = {
  id: string | null
  credentialId: string | null
  userId: string | null
  permissions: string | null
  createdAt: Date | null
}

export type CredentialShareMaxAggregateOutputType = {
  id: string | null
  credentialId: string | null
  userId: string | null
  permissions: string | null
  createdAt: Date | null
}

export type CredentialShareCountAggregateOutputType = {
  id: number
  credentialId: number
  userId: number
  permissions: number
  createdAt: number
  _all: number
}


export type CredentialShareMinAggregateInputType = {
  id?: true
  credentialId?: true
  userId?: true
  permissions?: true
  createdAt?: true
}

export type CredentialShareMaxAggregateInputType = {
  id?: true
  credentialId?: true
  userId?: true
  permissions?: true
  createdAt?: true
}

export type CredentialShareCountAggregateInputType = {
  id?: true
  credentialId?: true
  userId?: true
  permissions?: true
  createdAt?: true
  _all?: true
}

export type CredentialShareAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CredentialShare to aggregate.
   */
  where?: Prisma.CredentialShareWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CredentialShares to fetch.
   */
  orderBy?: Prisma.CredentialShareOrderByWithRelationInput | Prisma.CredentialShareOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CredentialShareWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CredentialShares from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CredentialShares.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned CredentialShares
  **/
  _count?: true | CredentialShareCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CredentialShareMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CredentialShareMaxAggregateInputType
}

export type GetCredentialShareAggregateType<T extends CredentialShareAggregateArgs> = {
      [P in keyof T & keyof AggregateCredentialShare]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCredentialShare[P]>
    : Prisma.GetScalarType<T[P], AggregateCredentialShare[P]>
}




export type CredentialShareGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CredentialShareWhereInput
  orderBy?: Prisma.CredentialShareOrderByWithAggregationInput | Prisma.CredentialShareOrderByWithAggregationInput[]
  by: Prisma.CredentialShareScalarFieldEnum[] | Prisma.CredentialShareScalarFieldEnum
  having?: Prisma.CredentialShareScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CredentialShareCountAggregateInputType | true
  _min?: CredentialShareMinAggregateInputType
  _max?: CredentialShareMaxAggregateInputType
}

export type CredentialShareGroupByOutputType = {
  id: string
  credentialId: string
  userId: string
  permissions: string
  createdAt: Date
  _count: CredentialShareCountAggregateOutputType | null
  _min: CredentialShareMinAggregateOutputType | null
  _max: CredentialShareMaxAggregateOutputType | null
}

type GetCredentialShareGroupByPayload<T extends CredentialShareGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CredentialShareGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CredentialShareGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CredentialShareGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CredentialShareGroupByOutputType[P]>
      }
    >
  >



export type CredentialShareWhereInput = {
  AND?: Prisma.CredentialShareWhereInput | Prisma.CredentialShareWhereInput[]
  OR?: Prisma.CredentialShareWhereInput[]
  NOT?: Prisma.CredentialShareWhereInput | Prisma.CredentialShareWhereInput[]
  id?: Prisma.StringFilter<"CredentialShare"> | string
  credentialId?: Prisma.StringFilter<"CredentialShare"> | string
  userId?: Prisma.StringFilter<"CredentialShare"> | string
  permissions?: Prisma.StringFilter<"CredentialShare"> | string
  createdAt?: Prisma.DateTimeFilter<"CredentialShare"> | Date | string
  credential?: Prisma.XOR<Prisma.CredentialScalarRelationFilter, Prisma.CredentialWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type CredentialShareOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  credentialId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  permissions?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  credential?: Prisma.CredentialOrderByWithRelationInput
  user?: Prisma.UserOrderByWithRelationInput
}

export type CredentialShareWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  credentialId_userId?: Prisma.CredentialShareCredentialIdUserIdCompoundUniqueInput
  AND?: Prisma.CredentialShareWhereInput | Prisma.CredentialShareWhereInput[]
  OR?: Prisma.CredentialShareWhereInput[]
  NOT?: Prisma.CredentialShareWhereInput | Prisma.CredentialShareWhereInput[]
  credentialId?: Prisma.StringFilter<"CredentialShare"> | string
  userId?: Prisma.StringFilter<"CredentialShare"> | string
  permissions?: Prisma.StringFilter<"CredentialShare"> | string
  createdAt?: Prisma.DateTimeFilter<"CredentialShare"> | Date | string
  credential?: Prisma.XOR<Prisma.CredentialScalarRelationFilter, Prisma.CredentialWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id" | "credentialId_userId">

export type CredentialShareOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  credentialId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  permissions?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.CredentialShareCountOrderByAggregateInput
  _max?: Prisma.CredentialShareMaxOrderByAggregateInput
  _min?: Prisma.CredentialShareMinOrderByAggregateInput
}

export type CredentialShareScalarWhereWithAggregatesInput = {
  AND?: Prisma.CredentialShareScalarWhereWithAggregatesInput | Prisma.CredentialShareScalarWhereWithAggregatesInput[]
  OR?: Prisma.CredentialShareScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CredentialShareScalarWhereWithAggregatesInput | Prisma.CredentialShareScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"CredentialShare"> | string
  credentialId?: Prisma.StringWithAggregatesFilter<"CredentialShare"> | string
  userId?: Prisma.StringWithAggregatesFilter<"CredentialShare"> | string
  permissions?: Prisma.StringWithAggregatesFilter<"CredentialShare"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"CredentialShare"> | Date | string
}

export type CredentialShareCreateInput = {
  id?: string
  permissions?: string
  createdAt?: Date | string
  credential: Prisma.CredentialCreateNestedOneWithoutSharesInput
  user: Prisma.UserCreateNestedOneWithoutSharedWithMeInput
}

export type CredentialShareUncheckedCreateInput = {
  id?: string
  credentialId: string
  userId: string
  permissions?: string
  createdAt?: Date | string
}

export type CredentialShareUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  permissions?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  credential?: Prisma.CredentialUpdateOneRequiredWithoutSharesNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutSharedWithMeNestedInput
}

export type CredentialShareUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  credentialId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  permissions?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CredentialShareCreateManyInput = {
  id?: string
  credentialId: string
  userId: string
  permissions?: string
  createdAt?: Date | string
}

export type CredentialShareUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  permissions?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CredentialShareUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  credentialId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  permissions?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CredentialShareListRelationFilter = {
  every?: Prisma.CredentialShareWhereInput
  some?: Prisma.CredentialShareWhereInput
  none?: Prisma.CredentialShareWhereInput
}

export type CredentialShareOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type CredentialShareCredentialIdUserIdCompoundUniqueInput = {
  credentialId: string
  userId: string
}

export type CredentialShareCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  credentialId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  permissions?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type CredentialShareMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  credentialId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  permissions?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type CredentialShareMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  credentialId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  permissions?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type CredentialShareCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.CredentialShareCreateWithoutUserInput, Prisma.CredentialShareUncheckedCreateWithoutUserInput> | Prisma.CredentialShareCreateWithoutUserInput[] | Prisma.CredentialShareUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.CredentialShareCreateOrConnectWithoutUserInput | Prisma.CredentialShareCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.CredentialShareCreateManyUserInputEnvelope
  connect?: Prisma.CredentialShareWhereUniqueInput | Prisma.CredentialShareWhereUniqueInput[]
}

export type CredentialShareUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.CredentialShareCreateWithoutUserInput, Prisma.CredentialShareUncheckedCreateWithoutUserInput> | Prisma.CredentialShareCreateWithoutUserInput[] | Prisma.CredentialShareUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.CredentialShareCreateOrConnectWithoutUserInput | Prisma.CredentialShareCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.CredentialShareCreateManyUserInputEnvelope
  connect?: Prisma.CredentialShareWhereUniqueInput | Prisma.CredentialShareWhereUniqueInput[]
}

export type CredentialShareUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.CredentialShareCreateWithoutUserInput, Prisma.CredentialShareUncheckedCreateWithoutUserInput> | Prisma.CredentialShareCreateWithoutUserInput[] | Prisma.CredentialShareUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.CredentialShareCreateOrConnectWithoutUserInput | Prisma.CredentialShareCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.CredentialShareUpsertWithWhereUniqueWithoutUserInput | Prisma.CredentialShareUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.CredentialShareCreateManyUserInputEnvelope
  set?: Prisma.CredentialShareWhereUniqueInput | Prisma.CredentialShareWhereUniqueInput[]
  disconnect?: Prisma.CredentialShareWhereUniqueInput | Prisma.CredentialShareWhereUniqueInput[]
  delete?: Prisma.CredentialShareWhereUniqueInput | Prisma.CredentialShareWhereUniqueInput[]
  connect?: Prisma.CredentialShareWhereUniqueInput | Prisma.CredentialShareWhereUniqueInput[]
  update?: Prisma.CredentialShareUpdateWithWhereUniqueWithoutUserInput | Prisma.CredentialShareUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.CredentialShareUpdateManyWithWhereWithoutUserInput | Prisma.CredentialShareUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.CredentialShareScalarWhereInput | Prisma.CredentialShareScalarWhereInput[]
}

export type CredentialShareUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.CredentialShareCreateWithoutUserInput, Prisma.CredentialShareUncheckedCreateWithoutUserInput> | Prisma.CredentialShareCreateWithoutUserInput[] | Prisma.CredentialShareUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.CredentialShareCreateOrConnectWithoutUserInput | Prisma.CredentialShareCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.CredentialShareUpsertWithWhereUniqueWithoutUserInput | Prisma.CredentialShareUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.CredentialShareCreateManyUserInputEnvelope
  set?: Prisma.CredentialShareWhereUniqueInput | Prisma.CredentialShareWhereUniqueInput[]
  disconnect?: Prisma.CredentialShareWhereUniqueInput | Prisma.CredentialShareWhereUniqueInput[]
  delete?: Prisma.CredentialShareWhereUniqueInput | Prisma.CredentialShareWhereUniqueInput[]
  connect?: Prisma.CredentialShareWhereUniqueInput | Prisma.CredentialShareWhereUniqueInput[]
  update?: Prisma.CredentialShareUpdateWithWhereUniqueWithoutUserInput | Prisma.CredentialShareUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.CredentialShareUpdateManyWithWhereWithoutUserInput | Prisma.CredentialShareUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.CredentialShareScalarWhereInput | Prisma.CredentialShareScalarWhereInput[]
}

export type CredentialShareCreateNestedManyWithoutCredentialInput = {
  create?: Prisma.XOR<Prisma.CredentialShareCreateWithoutCredentialInput, Prisma.CredentialShareUncheckedCreateWithoutCredentialInput> | Prisma.CredentialShareCreateWithoutCredentialInput[] | Prisma.CredentialShareUncheckedCreateWithoutCredentialInput[]
  connectOrCreate?: Prisma.CredentialShareCreateOrConnectWithoutCredentialInput | Prisma.CredentialShareCreateOrConnectWithoutCredentialInput[]
  createMany?: Prisma.CredentialShareCreateManyCredentialInputEnvelope
  connect?: Prisma.CredentialShareWhereUniqueInput | Prisma.CredentialShareWhereUniqueInput[]
}

export type CredentialShareUncheckedCreateNestedManyWithoutCredentialInput = {
  create?: Prisma.XOR<Prisma.CredentialShareCreateWithoutCredentialInput, Prisma.CredentialShareUncheckedCreateWithoutCredentialInput> | Prisma.CredentialShareCreateWithoutCredentialInput[] | Prisma.CredentialShareUncheckedCreateWithoutCredentialInput[]
  connectOrCreate?: Prisma.CredentialShareCreateOrConnectWithoutCredentialInput | Prisma.CredentialShareCreateOrConnectWithoutCredentialInput[]
  createMany?: Prisma.CredentialShareCreateManyCredentialInputEnvelope
  connect?: Prisma.CredentialShareWhereUniqueInput | Prisma.CredentialShareWhereUniqueInput[]
}

export type CredentialShareUpdateManyWithoutCredentialNestedInput = {
  create?: Prisma.XOR<Prisma.CredentialShareCreateWithoutCredentialInput, Prisma.CredentialShareUncheckedCreateWithoutCredentialInput> | Prisma.CredentialShareCreateWithoutCredentialInput[] | Prisma.CredentialShareUncheckedCreateWithoutCredentialInput[]
  connectOrCreate?: Prisma.CredentialShareCreateOrConnectWithoutCredentialInput | Prisma.CredentialShareCreateOrConnectWithoutCredentialInput[]
  upsert?: Prisma.CredentialShareUpsertWithWhereUniqueWithoutCredentialInput | Prisma.CredentialShareUpsertWithWhereUniqueWithoutCredentialInput[]
  createMany?: Prisma.CredentialShareCreateManyCredentialInputEnvelope
  set?: Prisma.CredentialShareWhereUniqueInput | Prisma.CredentialShareWhereUniqueInput[]
  disconnect?: Prisma.CredentialShareWhereUniqueInput | Prisma.CredentialShareWhereUniqueInput[]
  delete?: Prisma.CredentialShareWhereUniqueInput | Prisma.CredentialShareWhereUniqueInput[]
  connect?: Prisma.CredentialShareWhereUniqueInput | Prisma.CredentialShareWhereUniqueInput[]
  update?: Prisma.CredentialShareUpdateWithWhereUniqueWithoutCredentialInput | Prisma.CredentialShareUpdateWithWhereUniqueWithoutCredentialInput[]
  updateMany?: Prisma.CredentialShareUpdateManyWithWhereWithoutCredentialInput | Prisma.CredentialShareUpdateManyWithWhereWithoutCredentialInput[]
  deleteMany?: Prisma.CredentialShareScalarWhereInput | Prisma.CredentialShareScalarWhereInput[]
}

export type CredentialShareUncheckedUpdateManyWithoutCredentialNestedInput = {
  create?: Prisma.XOR<Prisma.CredentialShareCreateWithoutCredentialInput, Prisma.CredentialShareUncheckedCreateWithoutCredentialInput> | Prisma.CredentialShareCreateWithoutCredentialInput[] | Prisma.CredentialShareUncheckedCreateWithoutCredentialInput[]
  connectOrCreate?: Prisma.CredentialShareCreateOrConnectWithoutCredentialInput | Prisma.CredentialShareCreateOrConnectWithoutCredentialInput[]
  upsert?: Prisma.CredentialShareUpsertWithWhereUniqueWithoutCredentialInput | Prisma.CredentialShareUpsertWithWhereUniqueWithoutCredentialInput[]
  createMany?: Prisma.CredentialShareCreateManyCredentialInputEnvelope
  set?: Prisma.CredentialShareWhereUniqueInput | Prisma.CredentialShareWhereUniqueInput[]
  disconnect?: Prisma.CredentialShareWhereUniqueInput | Prisma.CredentialShareWhereUniqueInput[]
  delete?: Prisma.CredentialShareWhereUniqueInput | Prisma.CredentialShareWhereUniqueInput[]
  connect?: Prisma.CredentialShareWhereUniqueInput | Prisma.CredentialShareWhereUniqueInput[]
  update?: Prisma.CredentialShareUpdateWithWhereUniqueWithoutCredentialInput | Prisma.CredentialShareUpdateWithWhereUniqueWithoutCredentialInput[]
  updateMany?: Prisma.CredentialShareUpdateManyWithWhereWithoutCredentialInput | Prisma.CredentialShareUpdateManyWithWhereWithoutCredentialInput[]
  deleteMany?: Prisma.CredentialShareScalarWhereInput | Prisma.CredentialShareScalarWhereInput[]
}

export type CredentialShareCreateWithoutUserInput = {
  id?: string
  permissions?: string
  createdAt?: Date | string
  credential: Prisma.CredentialCreateNestedOneWithoutSharesInput
}

export type CredentialShareUncheckedCreateWithoutUserInput = {
  id?: string
  credentialId: string
  permissions?: string
  createdAt?: Date | string
}

export type CredentialShareCreateOrConnectWithoutUserInput = {
  where: Prisma.CredentialShareWhereUniqueInput
  create: Prisma.XOR<Prisma.CredentialShareCreateWithoutUserInput, Prisma.CredentialShareUncheckedCreateWithoutUserInput>
}

export type CredentialShareCreateManyUserInputEnvelope = {
  data: Prisma.CredentialShareCreateManyUserInput | Prisma.CredentialShareCreateManyUserInput[]
}

export type CredentialShareUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.CredentialShareWhereUniqueInput
  update: Prisma.XOR<Prisma.CredentialShareUpdateWithoutUserInput, Prisma.CredentialShareUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.CredentialShareCreateWithoutUserInput, Prisma.CredentialShareUncheckedCreateWithoutUserInput>
}

export type CredentialShareUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.CredentialShareWhereUniqueInput
  data: Prisma.XOR<Prisma.CredentialShareUpdateWithoutUserInput, Prisma.CredentialShareUncheckedUpdateWithoutUserInput>
}

export type CredentialShareUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.CredentialShareScalarWhereInput
  data: Prisma.XOR<Prisma.CredentialShareUpdateManyMutationInput, Prisma.CredentialShareUncheckedUpdateManyWithoutUserInput>
}

export type CredentialShareScalarWhereInput = {
  AND?: Prisma.CredentialShareScalarWhereInput | Prisma.CredentialShareScalarWhereInput[]
  OR?: Prisma.CredentialShareScalarWhereInput[]
  NOT?: Prisma.CredentialShareScalarWhereInput | Prisma.CredentialShareScalarWhereInput[]
  id?: Prisma.StringFilter<"CredentialShare"> | string
  credentialId?: Prisma.StringFilter<"CredentialShare"> | string
  userId?: Prisma.StringFilter<"CredentialShare"> | string
  permissions?: Prisma.StringFilter<"CredentialShare"> | string
  createdAt?: Prisma.DateTimeFilter<"CredentialShare"> | Date | string
}

export type CredentialShareCreateWithoutCredentialInput = {
  id?: string
  permissions?: string
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutSharedWithMeInput
}

export type CredentialShareUncheckedCreateWithoutCredentialInput = {
  id?: string
  userId: string
  permissions?: string
  createdAt?: Date | string
}

export type CredentialShareCreateOrConnectWithoutCredentialInput = {
  where: Prisma.CredentialShareWhereUniqueInput
  create: Prisma.XOR<Prisma.CredentialShareCreateWithoutCredentialInput, Prisma.CredentialShareUncheckedCreateWithoutCredentialInput>
}

export type CredentialShareCreateManyCredentialInputEnvelope = {
  data: Prisma.CredentialShareCreateManyCredentialInput | Prisma.CredentialShareCreateManyCredentialInput[]
}

export type CredentialShareUpsertWithWhereUniqueWithoutCredentialInput = {
  where: Prisma.CredentialShareWhereUniqueInput
  update: Prisma.XOR<Prisma.CredentialShareUpdateWithoutCredentialInput, Prisma.CredentialShareUncheckedUpdateWithoutCredentialInput>
  create: Prisma.XOR<Prisma.CredentialShareCreateWithoutCredentialInput, Prisma.CredentialShareUncheckedCreateWithoutCredentialInput>
}

export type CredentialShareUpdateWithWhereUniqueWithoutCredentialInput = {
  where: Prisma.CredentialShareWhereUniqueInput
  data: Prisma.XOR<Prisma.CredentialShareUpdateWithoutCredentialInput, Prisma.CredentialShareUncheckedUpdateWithoutCredentialInput>
}

export type CredentialShareUpdateManyWithWhereWithoutCredentialInput = {
  where: Prisma.CredentialShareScalarWhereInput
  data: Prisma.XOR<Prisma.CredentialShareUpdateManyMutationInput, Prisma.CredentialShareUncheckedUpdateManyWithoutCredentialInput>
}

export type CredentialShareCreateManyUserInput = {
  id?: string
  credentialId: string
  permissions?: string
  createdAt?: Date | string
}

export type CredentialShareUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  permissions?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  credential?: Prisma.CredentialUpdateOneRequiredWithoutSharesNestedInput
}

export type CredentialShareUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  credentialId?: Prisma.StringFieldUpdateOperationsInput | string
  permissions?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CredentialShareUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  credentialId?: Prisma.StringFieldUpdateOperationsInput | string
  permissions?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CredentialShareCreateManyCredentialInput = {
  id?: string
  userId: string
  permissions?: string
  createdAt?: Date | string
}

export type CredentialShareUpdateWithoutCredentialInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  permissions?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutSharedWithMeNestedInput
}

export type CredentialShareUncheckedUpdateWithoutCredentialInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  permissions?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CredentialShareUncheckedUpdateManyWithoutCredentialInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  permissions?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type CredentialShareSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  credentialId?: boolean
  userId?: boolean
  permissions?: boolean
  createdAt?: boolean
  credential?: boolean | Prisma.CredentialDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["credentialShare"]>

export type CredentialShareSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  credentialId?: boolean
  userId?: boolean
  permissions?: boolean
  createdAt?: boolean
  credential?: boolean | Prisma.CredentialDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["credentialShare"]>

export type CredentialShareSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  credentialId?: boolean
  userId?: boolean
  permissions?: boolean
  createdAt?: boolean
  credential?: boolean | Prisma.CredentialDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["credentialShare"]>

export type CredentialShareSelectScalar = {
  id?: boolean
  credentialId?: boolean
  userId?: boolean
  permissions?: boolean
  createdAt?: boolean
}

export type CredentialShareOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "credentialId" | "userId" | "permissions" | "createdAt", ExtArgs["result"]["credentialShare"]>
export type CredentialShareInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  credential?: boolean | Prisma.CredentialDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type CredentialShareIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  credential?: boolean | Prisma.CredentialDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type CredentialShareIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  credential?: boolean | Prisma.CredentialDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $CredentialSharePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "CredentialShare"
  objects: {
    credential: Prisma.$CredentialPayload<ExtArgs>
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    credentialId: string
    userId: string
    permissions: string
    createdAt: Date
  }, ExtArgs["result"]["credentialShare"]>
  composites: {}
}

export type CredentialShareGetPayload<S extends boolean | null | undefined | CredentialShareDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CredentialSharePayload, S>

export type CredentialShareCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CredentialShareFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CredentialShareCountAggregateInputType | true
  }

export interface CredentialShareDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['CredentialShare'], meta: { name: 'CredentialShare' } }
  /**
   * Find zero or one CredentialShare that matches the filter.
   * @param {CredentialShareFindUniqueArgs} args - Arguments to find a CredentialShare
   * @example
   * // Get one CredentialShare
   * const credentialShare = await prisma.credentialShare.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CredentialShareFindUniqueArgs>(args: Prisma.SelectSubset<T, CredentialShareFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CredentialShareClient<runtime.Types.Result.GetResult<Prisma.$CredentialSharePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one CredentialShare that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CredentialShareFindUniqueOrThrowArgs} args - Arguments to find a CredentialShare
   * @example
   * // Get one CredentialShare
   * const credentialShare = await prisma.credentialShare.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CredentialShareFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CredentialShareFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CredentialShareClient<runtime.Types.Result.GetResult<Prisma.$CredentialSharePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CredentialShare that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CredentialShareFindFirstArgs} args - Arguments to find a CredentialShare
   * @example
   * // Get one CredentialShare
   * const credentialShare = await prisma.credentialShare.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CredentialShareFindFirstArgs>(args?: Prisma.SelectSubset<T, CredentialShareFindFirstArgs<ExtArgs>>): Prisma.Prisma__CredentialShareClient<runtime.Types.Result.GetResult<Prisma.$CredentialSharePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CredentialShare that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CredentialShareFindFirstOrThrowArgs} args - Arguments to find a CredentialShare
   * @example
   * // Get one CredentialShare
   * const credentialShare = await prisma.credentialShare.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CredentialShareFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CredentialShareFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CredentialShareClient<runtime.Types.Result.GetResult<Prisma.$CredentialSharePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more CredentialShares that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CredentialShareFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CredentialShares
   * const credentialShares = await prisma.credentialShare.findMany()
   * 
   * // Get first 10 CredentialShares
   * const credentialShares = await prisma.credentialShare.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const credentialShareWithIdOnly = await prisma.credentialShare.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CredentialShareFindManyArgs>(args?: Prisma.SelectSubset<T, CredentialShareFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CredentialSharePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a CredentialShare.
   * @param {CredentialShareCreateArgs} args - Arguments to create a CredentialShare.
   * @example
   * // Create one CredentialShare
   * const CredentialShare = await prisma.credentialShare.create({
   *   data: {
   *     // ... data to create a CredentialShare
   *   }
   * })
   * 
   */
  create<T extends CredentialShareCreateArgs>(args: Prisma.SelectSubset<T, CredentialShareCreateArgs<ExtArgs>>): Prisma.Prisma__CredentialShareClient<runtime.Types.Result.GetResult<Prisma.$CredentialSharePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many CredentialShares.
   * @param {CredentialShareCreateManyArgs} args - Arguments to create many CredentialShares.
   * @example
   * // Create many CredentialShares
   * const credentialShare = await prisma.credentialShare.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CredentialShareCreateManyArgs>(args?: Prisma.SelectSubset<T, CredentialShareCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many CredentialShares and returns the data saved in the database.
   * @param {CredentialShareCreateManyAndReturnArgs} args - Arguments to create many CredentialShares.
   * @example
   * // Create many CredentialShares
   * const credentialShare = await prisma.credentialShare.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many CredentialShares and only return the `id`
   * const credentialShareWithIdOnly = await prisma.credentialShare.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CredentialShareCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CredentialShareCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CredentialSharePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a CredentialShare.
   * @param {CredentialShareDeleteArgs} args - Arguments to delete one CredentialShare.
   * @example
   * // Delete one CredentialShare
   * const CredentialShare = await prisma.credentialShare.delete({
   *   where: {
   *     // ... filter to delete one CredentialShare
   *   }
   * })
   * 
   */
  delete<T extends CredentialShareDeleteArgs>(args: Prisma.SelectSubset<T, CredentialShareDeleteArgs<ExtArgs>>): Prisma.Prisma__CredentialShareClient<runtime.Types.Result.GetResult<Prisma.$CredentialSharePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one CredentialShare.
   * @param {CredentialShareUpdateArgs} args - Arguments to update one CredentialShare.
   * @example
   * // Update one CredentialShare
   * const credentialShare = await prisma.credentialShare.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CredentialShareUpdateArgs>(args: Prisma.SelectSubset<T, CredentialShareUpdateArgs<ExtArgs>>): Prisma.Prisma__CredentialShareClient<runtime.Types.Result.GetResult<Prisma.$CredentialSharePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more CredentialShares.
   * @param {CredentialShareDeleteManyArgs} args - Arguments to filter CredentialShares to delete.
   * @example
   * // Delete a few CredentialShares
   * const { count } = await prisma.credentialShare.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CredentialShareDeleteManyArgs>(args?: Prisma.SelectSubset<T, CredentialShareDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CredentialShares.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CredentialShareUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CredentialShares
   * const credentialShare = await prisma.credentialShare.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CredentialShareUpdateManyArgs>(args: Prisma.SelectSubset<T, CredentialShareUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CredentialShares and returns the data updated in the database.
   * @param {CredentialShareUpdateManyAndReturnArgs} args - Arguments to update many CredentialShares.
   * @example
   * // Update many CredentialShares
   * const credentialShare = await prisma.credentialShare.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more CredentialShares and only return the `id`
   * const credentialShareWithIdOnly = await prisma.credentialShare.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CredentialShareUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CredentialShareUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CredentialSharePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one CredentialShare.
   * @param {CredentialShareUpsertArgs} args - Arguments to update or create a CredentialShare.
   * @example
   * // Update or create a CredentialShare
   * const credentialShare = await prisma.credentialShare.upsert({
   *   create: {
   *     // ... data to create a CredentialShare
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CredentialShare we want to update
   *   }
   * })
   */
  upsert<T extends CredentialShareUpsertArgs>(args: Prisma.SelectSubset<T, CredentialShareUpsertArgs<ExtArgs>>): Prisma.Prisma__CredentialShareClient<runtime.Types.Result.GetResult<Prisma.$CredentialSharePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of CredentialShares.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CredentialShareCountArgs} args - Arguments to filter CredentialShares to count.
   * @example
   * // Count the number of CredentialShares
   * const count = await prisma.credentialShare.count({
   *   where: {
   *     // ... the filter for the CredentialShares we want to count
   *   }
   * })
  **/
  count<T extends CredentialShareCountArgs>(
    args?: Prisma.Subset<T, CredentialShareCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CredentialShareCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a CredentialShare.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CredentialShareAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CredentialShareAggregateArgs>(args: Prisma.Subset<T, CredentialShareAggregateArgs>): Prisma.PrismaPromise<GetCredentialShareAggregateType<T>>

  /**
   * Group by CredentialShare.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CredentialShareGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CredentialShareGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CredentialShareGroupByArgs['orderBy'] }
      : { orderBy?: CredentialShareGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CredentialShareGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCredentialShareGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the CredentialShare model
 */
readonly fields: CredentialShareFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CredentialShare.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CredentialShareClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  credential<T extends Prisma.CredentialDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CredentialDefaultArgs<ExtArgs>>): Prisma.Prisma__CredentialClient<runtime.Types.Result.GetResult<Prisma.$CredentialPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the CredentialShare model
 */
export interface CredentialShareFieldRefs {
  readonly id: Prisma.FieldRef<"CredentialShare", 'String'>
  readonly credentialId: Prisma.FieldRef<"CredentialShare", 'String'>
  readonly userId: Prisma.FieldRef<"CredentialShare", 'String'>
  readonly permissions: Prisma.FieldRef<"CredentialShare", 'String'>
  readonly createdAt: Prisma.FieldRef<"CredentialShare", 'DateTime'>
}
    

// Custom InputTypes
/**
 * CredentialShare findUnique
 */
export type CredentialShareFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CredentialShare
   */
  select?: Prisma.CredentialShareSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CredentialShare
   */
  omit?: Prisma.CredentialShareOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CredentialShareInclude<ExtArgs> | null
  /**
   * Filter, which CredentialShare to fetch.
   */
  where: Prisma.CredentialShareWhereUniqueInput
}

/**
 * CredentialShare findUniqueOrThrow
 */
export type CredentialShareFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CredentialShare
   */
  select?: Prisma.CredentialShareSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CredentialShare
   */
  omit?: Prisma.CredentialShareOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CredentialShareInclude<ExtArgs> | null
  /**
   * Filter, which CredentialShare to fetch.
   */
  where: Prisma.CredentialShareWhereUniqueInput
}

/**
 * CredentialShare findFirst
 */
export type CredentialShareFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CredentialShare
   */
  select?: Prisma.CredentialShareSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CredentialShare
   */
  omit?: Prisma.CredentialShareOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CredentialShareInclude<ExtArgs> | null
  /**
   * Filter, which CredentialShare to fetch.
   */
  where?: Prisma.CredentialShareWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CredentialShares to fetch.
   */
  orderBy?: Prisma.CredentialShareOrderByWithRelationInput | Prisma.CredentialShareOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CredentialShares.
   */
  cursor?: Prisma.CredentialShareWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CredentialShares from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CredentialShares.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CredentialShares.
   */
  distinct?: Prisma.CredentialShareScalarFieldEnum | Prisma.CredentialShareScalarFieldEnum[]
}

/**
 * CredentialShare findFirstOrThrow
 */
export type CredentialShareFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CredentialShare
   */
  select?: Prisma.CredentialShareSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CredentialShare
   */
  omit?: Prisma.CredentialShareOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CredentialShareInclude<ExtArgs> | null
  /**
   * Filter, which CredentialShare to fetch.
   */
  where?: Prisma.CredentialShareWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CredentialShares to fetch.
   */
  orderBy?: Prisma.CredentialShareOrderByWithRelationInput | Prisma.CredentialShareOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CredentialShares.
   */
  cursor?: Prisma.CredentialShareWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CredentialShares from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CredentialShares.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CredentialShares.
   */
  distinct?: Prisma.CredentialShareScalarFieldEnum | Prisma.CredentialShareScalarFieldEnum[]
}

/**
 * CredentialShare findMany
 */
export type CredentialShareFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CredentialShare
   */
  select?: Prisma.CredentialShareSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CredentialShare
   */
  omit?: Prisma.CredentialShareOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CredentialShareInclude<ExtArgs> | null
  /**
   * Filter, which CredentialShares to fetch.
   */
  where?: Prisma.CredentialShareWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CredentialShares to fetch.
   */
  orderBy?: Prisma.CredentialShareOrderByWithRelationInput | Prisma.CredentialShareOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing CredentialShares.
   */
  cursor?: Prisma.CredentialShareWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CredentialShares from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CredentialShares.
   */
  skip?: number
  distinct?: Prisma.CredentialShareScalarFieldEnum | Prisma.CredentialShareScalarFieldEnum[]
}

/**
 * CredentialShare create
 */
export type CredentialShareCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CredentialShare
   */
  select?: Prisma.CredentialShareSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CredentialShare
   */
  omit?: Prisma.CredentialShareOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CredentialShareInclude<ExtArgs> | null
  /**
   * The data needed to create a CredentialShare.
   */
  data: Prisma.XOR<Prisma.CredentialShareCreateInput, Prisma.CredentialShareUncheckedCreateInput>
}

/**
 * CredentialShare createMany
 */
export type CredentialShareCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many CredentialShares.
   */
  data: Prisma.CredentialShareCreateManyInput | Prisma.CredentialShareCreateManyInput[]
}

/**
 * CredentialShare createManyAndReturn
 */
export type CredentialShareCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CredentialShare
   */
  select?: Prisma.CredentialShareSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CredentialShare
   */
  omit?: Prisma.CredentialShareOmit<ExtArgs> | null
  /**
   * The data used to create many CredentialShares.
   */
  data: Prisma.CredentialShareCreateManyInput | Prisma.CredentialShareCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CredentialShareIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * CredentialShare update
 */
export type CredentialShareUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CredentialShare
   */
  select?: Prisma.CredentialShareSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CredentialShare
   */
  omit?: Prisma.CredentialShareOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CredentialShareInclude<ExtArgs> | null
  /**
   * The data needed to update a CredentialShare.
   */
  data: Prisma.XOR<Prisma.CredentialShareUpdateInput, Prisma.CredentialShareUncheckedUpdateInput>
  /**
   * Choose, which CredentialShare to update.
   */
  where: Prisma.CredentialShareWhereUniqueInput
}

/**
 * CredentialShare updateMany
 */
export type CredentialShareUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update CredentialShares.
   */
  data: Prisma.XOR<Prisma.CredentialShareUpdateManyMutationInput, Prisma.CredentialShareUncheckedUpdateManyInput>
  /**
   * Filter which CredentialShares to update
   */
  where?: Prisma.CredentialShareWhereInput
  /**
   * Limit how many CredentialShares to update.
   */
  limit?: number
}

/**
 * CredentialShare updateManyAndReturn
 */
export type CredentialShareUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CredentialShare
   */
  select?: Prisma.CredentialShareSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CredentialShare
   */
  omit?: Prisma.CredentialShareOmit<ExtArgs> | null
  /**
   * The data used to update CredentialShares.
   */
  data: Prisma.XOR<Prisma.CredentialShareUpdateManyMutationInput, Prisma.CredentialShareUncheckedUpdateManyInput>
  /**
   * Filter which CredentialShares to update
   */
  where?: Prisma.CredentialShareWhereInput
  /**
   * Limit how many CredentialShares to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CredentialShareIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * CredentialShare upsert
 */
export type CredentialShareUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CredentialShare
   */
  select?: Prisma.CredentialShareSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CredentialShare
   */
  omit?: Prisma.CredentialShareOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CredentialShareInclude<ExtArgs> | null
  /**
   * The filter to search for the CredentialShare to update in case it exists.
   */
  where: Prisma.CredentialShareWhereUniqueInput
  /**
   * In case the CredentialShare found by the `where` argument doesn't exist, create a new CredentialShare with this data.
   */
  create: Prisma.XOR<Prisma.CredentialShareCreateInput, Prisma.CredentialShareUncheckedCreateInput>
  /**
   * In case the CredentialShare was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CredentialShareUpdateInput, Prisma.CredentialShareUncheckedUpdateInput>
}

/**
 * CredentialShare delete
 */
export type CredentialShareDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CredentialShare
   */
  select?: Prisma.CredentialShareSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CredentialShare
   */
  omit?: Prisma.CredentialShareOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CredentialShareInclude<ExtArgs> | null
  /**
   * Filter which CredentialShare to delete.
   */
  where: Prisma.CredentialShareWhereUniqueInput
}

/**
 * CredentialShare deleteMany
 */
export type CredentialShareDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CredentialShares to delete
   */
  where?: Prisma.CredentialShareWhereInput
  /**
   * Limit how many CredentialShares to delete.
   */
  limit?: number
}

/**
 * CredentialShare without action
 */
export type CredentialShareDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CredentialShare
   */
  select?: Prisma.CredentialShareSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CredentialShare
   */
  omit?: Prisma.CredentialShareOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CredentialShareInclude<ExtArgs> | null
}
